name: CI on Nix

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(fromJSON('["refs/heads/develop","refs/heads/master"]'), github.ref) }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            cores = 0
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: nicknovitski/nix-develop@v1
      - uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-dune-${{ hasFiles('**/flake.lock')}}-${{ hashFiles('**/dune-project') }}
      - name: Check for format
        run: |
          # shellcheck disable=SC2046
          nix fmt $(git ls-files '*.nix')
          dune fmt
          git diff --exit-code
          actionlint
      - name: Run tests
        run: |
          dune test --debug-backtrace

  documentation:
    needs: build
    if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            cores = 0
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: nicknovitski/nix-develop@v1
      - uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-dune-${{ hasFiles('**/flake.lock')}}-${{ hashFiles('**/dune-project') }}
      - name: Build docs
        run: |
          dune build @doc
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/default/_doc/_html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
