name: Release

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions: write-all
env:
  GIT_EMAIL: "s1311350@gmail.com"
  GIT_NAME: "Satoru Kawahara"
  GITHUB_ID: "Nymphium"
  GITHUB_REPO_NAME: "oenv"
  DUNE_RELEASE: "nix run .#dune-release --"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Release
        uses: softprops/action-gh-release@v2

  publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v5
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> "$GITHUB_ENV"
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            cores = 0
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: nicknovitski/nix-develop@v1
        with:
          arguments: .#ci
      - name: Install deps
        run: |
          git config --global user.email "${{ env.GIT_EMAIL }}"
          git config --global user.name "${{ env.GIT_NAME }}"
          git config --global url."https://github.com/".pushInsteadOf "git@github.com:"
          echo "machine github.com login ${{ env.GITHUB_ID }} password ${{ secrets.RELEASE_TOKEN }}" > ~/.netrc
          mkdir -p "$HOME/git"
          git clone https://github.com/${{ env.GITHUB_ID }}/opam-repository "$HOME/git/opam-repository"
          mkdir -p "$HOME/.config/dune"
          cat <<EOL > "$HOME/.config/dune/release.yml"
          remote: https://github.com/${{ env.GITHUB_ID }}/opam-repository
          local: $HOME/git/opam-repository
          EOL
          cat <<'EOL' > CHANGES.md
          - See `git log` (#NA, @NA)
          EOL
      - name: Build release contents
        run: |
          ${{ env.DUNE_RELEASE }} distrib --skip-lint --skip-build
          ${{ env.DUNE_RELEASE }} opam pkg
          ${{ env.DUNE_RELEASE }} publish -y --token ${{ secrets.RELEASE_TOKEN }}
          ${{ env.DUNE_RELEASE }} opam submit -y -m "See git log" --no-auto-open --token ${{ secrets.RELEASE_TOKEN }}
