name: Release

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions: write-all
env:
  GIT_EMAIL: "s1311350@gmail.com"
  GIT_NAME: "Satoru Kawahara"
  GITHUB_ID: "Nymphium"
  DUNE_RELEASE: "nix run .#dune-release --"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v5
      - run: |
          {
            echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}"
            echo "DUNE_RELEASE_GITHUB_TOKEN=${{ secrets.RELEASE_TOKEN }}"
            echo "DUNE_RELEASE_OPAM_REPO=${{ env.GITHUB_ID }}/opam-repository"
            echo "DUNE_RELEASE_REMOTE_REPO=https://github.com/${{ env.GITHUB_ID }}/opam-repository"
            echo "DUNE_RELEASE_LOCAL_REPO=$HOME/git/opam-repository"
          } >> "$GITHUB_ENV"
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            cores = 0
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: nicknovitski/nix-develop@v1
        with:
          arguments: .#ci
      - name: Set up for dune-release
        run: |
          git config --global user.email "${{ env.GIT_EMAIL }}"
          git config --global user.name "${{ env.GIT_NAME }}"
          git config --global url."https://github.com/".pushInsteadOf "git@github.com:"
          echo "machine github.com login ${{ env.GITHUB_ID }} password ${{ secrets.RELEASE_TOKEN }}" > ~/.netrc
          mkdir -p "$HOME/git"
          git clone ${{ env.DUNE_RELEASE_REMOTE_REPO }} ${{ env.DUNE_RELEASE_LOCAL_REPO }}
          cat <<'EOL' > CHANGES.md
          # HEAD
          - See `git log`.
          EOL
      - name: Publish Release PR to opam-repository
        run: |
          ${{ env.DUNE_RELEASE }} distrib --skip-lint --skip-build
          ${{ env.DUNE_RELEASE }} opam pkg
          ${{ env.DUNE_RELEASE }} publish -y
          ${{ env.DUNE_RELEASE }} opam submit -y --no-auto-open
